name: GitHub Action Test Run - Karate Runner

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - qa
          - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # setup
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      # clean test
      - name: Clean tests result
        run: ./gradlew clean

      # run tests
      - name: Run tests
        continue-on-error: false
        run: ./gradlew test --tests "org.example.karate_tests.TestRunner.run" -Dkarate.env=${{ inputs.environment }}

      # Upload Karate-Summary Report
      - name: Upload karate reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: karate-reports
          path: build/karate-reports
